export const COMMENT_ADD_REQUEST = 'COMMENT_ADD_REQUEST'
export const COMMENT_ADD_SUCCESS = 'COMMENT_ADD_SUCCESS'
export const COMMENT_ADD_FAIL = 'COMMENT_ADD_FAIL'


export const COMMENT_DETAILS_REQUEST = 'COMMENT_DETAILS_REQUEST'
export const COMMENT_DETAILS_SUCCESS = 'COMMENT_DETAILS_SUCCESS'
export const COMMENT_DETAILS_FAIL = 'COMMENT_DETAILS_FAIL'


export const COMMENT_UPDATE_REQUEST = 'COMMENT_UPDATE_REQUEST'
export const COMMENT_UPDATE_SUCCESS = 'COMMENT_UPDATE_SUCCESS'
export const COMMENT_UPDATE_FAIL = 'COMMENT_UPDATE_FAIL'

